### ISSUE TITLE
报Class 'Co\Redis' not found in /www/jin-chat/App/Utility/Pool/RedisObject.php:14这个错

### ISSUE THREAD

**Issue by xingyu-Lu** [Double-Jin/jin-chat#6]
[DEBUG][error]:[Uncaught Error: Class 'Co\Redis' not found in /www/jin-chat/App/Utility/Pool/RedisObject.php:14
Stack trace:
#0 /www/jin-chat/vendor/composer/ClassLoader.php(444): include()
#1 /www/jin-chat/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/jin-chat/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Utility\\Poo...')
#3 /www/jin-chat/App/Utility/Pool/RedisPool.php(20): spl_autoload_call('App\\Utility\\Poo...')
#4 /www/jin-chat/vendor/easyswoole/component/src/Pool/AbstractPool.php(238): App\Utility\Pool\RedisPool->createObject()
#5 /www/jin-chat/vendor/easyswoole/component/src/Pool/AbstractPool.php(197): EasySwoole\Component\Pool\AbstractPool->initObject()
#6 /www/jin-chat/vendor/easyswoole/component/src/Pool/AbstractPool.php(189): EasySwoole\Component\Pool\AbstractPool->keepMin(5)
#7 {main}
  thrown at file:/www/jin-chat/App/Utility/Pool/RedisObject.php line:14]

**Comment by sun649936757** [comment]
the line 14, replace  (class RedisObject extends \Redis implements PoolObjectInterface) , it is ojbk
